server:
  port: 8083
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/parkserver?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
websocket:
  maxTimeout: 120000
qingparkserver:
  id: 1
  name: 华东服务器
  api: /park
  maxsize: 100

register:
  onlineapi: ws://127.0.0.1/1000