server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/park?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
register:
  api: http://localhost:8083/server/balanced_server